---
name: ✨ Feature request
description: Suggest an idea for setuptools
title: '[FR] '
labels:
- enhancement
- Needs Triage
issue_body: false  # default: true, adds a classic WSYWIG textarea, if on

body:
- type: markdown
  attributes:
    value: >
      **Thank you for wanting to suggest a feature for setuptools!**


      💡
      Before you go ahead with your request, please first consider if it wouldn't be
      better suited for a plugin. As a general rule of thumb, any feature that is only
      of interest to a small sub group should be moved into a plugin. Only such features
      that are of interest to a majority of OctoPrint's users will be implemented as
      part of the core itself.

      <details>
        <summary>
          <center>

          ❗ Every change breaks someone's workflow.
          </center>
        </summary>

        [![❗ Every change breaks someone's workflow.](https://imgs.xkcd.com/comics/workflow.png)](https://xkcd.com/1172/)
      </details>


      ⚠
      Verify first that your idea is not [already requested on GitHub][issue search].



      [issue search]: https://github.com/pypa/setuptools/search?q=is%3Aissue&type=issues

- type: textarea
  attributes:
    label: What's the problem this feature will solve?
    description: >-
      What are you trying to do, that you are unable to achieve
      with setuptools as it currently stands?

- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: |
      Clear and concise description of what you want to happen.

      Provide examples of real world use cases that this would enable and how it solves the problem described above.

- type: textarea
  attributes:
    label: Alternative Solutions
    description: |
      Have you tried to workaround the problem using pip or other tools? Or a different approach to solving this issue? Please elaborate here.

- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other context, links, etc. about the feature here.
      Describe how the feature would be used, why it is needed and what it would solve.

      **HINT:** You can paste https://gist.github.com links for larger files.


- type: checkboxes
  attributes:
    label: Code of Conduct
    description: |
      Read the [PSF Code of Conduct][CoC] first.

      [CoC]: https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md
    options:
    - label: I agree to follow the PSF Code of Conduct
      required: true
...
